import java.util.List;
import java.util.ArrayList;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.BufferedReader;
import java.net.URL;
import java.net.URI;
import javax.swing.JOptionPane;
import java.net.URISyntaxException;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.Insets;
import java.awt.Dimension;
import javax.swing.KeyStroke;
import java.awt.Container;
import java.awt.FlowLayout;
import java.net.MalformedURLException;
import java.lang.StringBuilder;
import javax.swing.ImageIcon;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JScrollPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.GraphicsEnvironment;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.BoxLayout;
import java.awt.Color;
import javax.swing.border.LineBorder;
import javax.swing.BorderFactory;
import javax.swing.border.EmptyBorder;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JButton;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JTextArea;

class VP2CPConverter
{
   JFrame fr = new JFrame();
   JTextArea input = new JTextArea();
   JButton button = new JButton("Convert");
   JPanel panel = new JPanel();
   JPanel buttonHolder = new JPanel();
   JLabel label = new JLabel("Place your Virtual Piano sheet music here:");
   JDialog classicSheet = new JDialog(fr,"Converted Sheet Music", JDialog.ModalityType.APPLICATION_MODAL);
   JPanel dialogPnl = new JPanel(new FlowLayout());
   JScrollPane scrollPane = new JScrollPane(input,JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
   JScrollPane scrollPane2 = new JScrollPane(dialogPnl,JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
   int numImages = 0;
   ImageIcon C3;
   ImageIcon D3;
   ImageIcon E3;
   ImageIcon F3;
   ImageIcon G3;
   ImageIcon A3;
   ImageIcon B3;
   ImageIcon C4;
   ImageIcon D4;
   ImageIcon E4;
   ImageIcon F4;
   ImageIcon G4;
   ImageIcon A4;
   ImageIcon B4;
   ImageIcon C5;
   ImageIcon D5;
   ImageIcon E5;
   ImageIcon F5;
   ImageIcon G5;
   ImageIcon A5;
   ImageIcon B5;
   ImageIcon C6;
   ImageIcon D6;
   ImageIcon E6;
   ImageIcon F6;
   ImageIcon G6;
   ImageIcon A6;
   ImageIcon B6;
   ImageIcon C7;
   ImageIcon D7;
   ImageIcon E7;
   ImageIcon F7;
   ImageIcon G7;
   ImageIcon A7;
   ImageIcon B7;
   ImageIcon C8;
   ImageIcon C3Sharp;
   ImageIcon D3Sharp;
   ImageIcon F3Sharp;
   ImageIcon G3Sharp;
   ImageIcon A3Sharp;
   ImageIcon C4Sharp;
   ImageIcon D4Sharp;
   ImageIcon F4Sharp;
   ImageIcon G4Sharp;
   ImageIcon A4Sharp;
   ImageIcon C5Sharp;
   ImageIcon D5Sharp;
   ImageIcon F5Sharp;
   ImageIcon G5Sharp;
   ImageIcon A5Sharp;
   ImageIcon C6Sharp;
   ImageIcon D6Sharp;
   ImageIcon F6Sharp;
   ImageIcon G6Sharp;
   ImageIcon A6Sharp;
   ImageIcon C7Sharp;
   ImageIcon D7Sharp;
   ImageIcon F7Sharp;
   ImageIcon G7Sharp;
   ImageIcon A7Sharp;
   ImageIcon C8Sharp;
   
   public VP2CPConverter()
   {
      C3 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/c3.png"));
      D3 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/d3.png"));
      E3 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/e3.png"));
      F3 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/f3.png"));
      G3 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/g3.png"));
      A3 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/a3.png"));
      B3 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/b3.png"));
      C4 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/c4.png"));
      D4 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/d4.png"));
      E4 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/e4.png"));
      F4 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/f4.png"));
      G4 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/g4.png"));
      A4 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/a4.png"));
      B4 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/b4.png"));
      C5 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/c5.png"));
      D5 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/d5.png"));
      E5 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/e5.png"));
      F5 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/f5.png"));
      G5 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/g5.png"));
      A5 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/a5.png"));
      B5 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/b5.png"));
      C6 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/c6.png"));
      D6 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/d6.png"));
      E6 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/e6.png"));
      F6 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/f6.png"));
      G6 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/g6.png"));
      A6 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/a6.png"));
      B6 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/b6.png"));
      C7 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/c7.png"));
      D7 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/d7.png"));
      E7 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/e7.png"));
      F7 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/f7.png"));
      G7 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/g7.png"));
      A7 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/a7.png"));
      B7 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/b7.png"));
      C8 = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/c8.png"));
      C3Sharp = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/c3#.png"));
      D3Sharp = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/d3#.png"));
      F3Sharp = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/f3#.png"));
      G3Sharp = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/g3#.png"));
      A3Sharp = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/a3#.png"));
      C4Sharp = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/c4#.png"));
      D4Sharp = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/d4#.png"));
      F4Sharp = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/f4#.png"));
      G4Sharp = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/g4#.png"));
      A4Sharp = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/a4#.png"));
      C5Sharp = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/c5#.png"));
      D5Sharp = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/d5#.png"));
      F5Sharp = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/f5#.png"));
      G5Sharp = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/g5#.png"));
      A5Sharp = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/a5#.png"));
      C6Sharp = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/c6#.png"));
      D6Sharp = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/d6#.png"));
      F6Sharp = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/f6#.png"));
      G6Sharp = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/g6#.png"));
      A6Sharp = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/a6#.png"));
      C7Sharp = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/c7#.png"));
      D7Sharp = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/d7#.png"));
      F7Sharp = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/f7#.png"));
      G7Sharp = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/g7#.png"));
      A7Sharp = new ImageIcon(VP2CPConverter.class.getClassLoader().getResource("images/a7#.png"));
      fr.setTitle("VP2CP Converter");
      fr.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      fr.setSize(300,300);
      WindowPositioner.setLocation(fr,WindowPositioner.CENTER,true);
      fr.setVisible(true);
      input.setLineWrap(true);
      buttonHolder.setBorder(new EmptyBorder(3,0,0,0));
      buttonHolder.add(button);
      panel.setLayout(new BorderLayout());
      panel.add(label,BorderLayout.NORTH);
      panel.add(scrollPane,BorderLayout.CENTER);
      panel.add(buttonHolder, BorderLayout.SOUTH);
      ((JComponent)fr.getContentPane()).setBorder(new EmptyBorder(15,10,3,10));
      fr.add(panel);
      button.addActionListener(
         new ActionListener(){
            public void actionPerformed(ActionEvent e)
            {
               for(Character c: input.getText().toCharArray())
               {
                  ImageIcon icon = null;
                  switch(c)
                  {
                     case '1': icon=C3; break;
                     case '2': icon=D3; break;
                     case '3': icon=E3; break;
                     case '4': icon=F3; break;
                     case '5': icon=G3; break;
                     case '6': icon=A3; break;
                     case '7': icon=B3; break;
                     case '8': icon=C4; break;
                     case '9': icon=D4; break;
                     case '0': icon=E4; break;
                     case 'q': icon=F4; break;
                     case 'w': icon=G4; break;
                     case 'e': icon=A4; break;
                     case 'r': icon=B4; break;
                     case 't': icon=C5; break;
                     case 'y': icon=D5; break;
                     case 'u': icon=E5; break;
                     case 'i': icon=F5; break;
                     case 'o': icon=G5; break;
                     case 'p': icon=A5; break;
                     case 'a': icon=B5; break;
                     case 's': icon=C6; break;
                     case 'd': icon=D6; break;
                     case 'f': icon=E6; break;
                     case 'g': icon=F6; break;
                     case 'h': icon=G6; break;
                     case 'j': icon=A6; break;
                     case 'k': icon=B6; break;
                     case 'l': icon=C7; break;
                     case 'z': icon=D7; break;
                     case 'x': icon=E7; break;
                     case 'c': icon=F7; break;
                     case 'v': icon=G7; break;
                     case 'b': icon=A7; break;
                     case 'n': icon=B7; break;
                     case 'm': icon=C8; break;
                     case '!': icon=C3Sharp; break;
                     case '@': icon=D3Sharp; break;
                     case '$': icon=F3Sharp; break;
                     case '%': icon=G3Sharp; break;
                     case '^': icon=A3Sharp; break;
                     case '*': icon=C4Sharp; break;
                     case '(': icon=D4Sharp; break;
                     case 'Q': icon=F4Sharp; break;
                     case 'W': icon=G4Sharp; break;
                     case 'E': icon=A4Sharp; break;
                     case 'T': icon=C5Sharp; break;
                     case 'Y': icon=D5Sharp; break;
                     case 'I': icon=F5Sharp; break;
                     case 'O': icon=G5Sharp; break;
                     case 'P': icon=A5Sharp; break;
                     case 'S': icon=C6Sharp; break;
                     case 'D': icon=D6Sharp; break;
                     case 'G': icon=F6Sharp; break;
                     case 'H': icon=G6Sharp; break;
                     case 'J': icon=A6Sharp; break;
                     case 'L': icon=C7Sharp; break;
                     case 'Z': icon=D7Sharp; break;
                     case 'C': icon=F7Sharp; break;
                     case 'V': icon=G7Sharp; break;
                     case 'B': icon=A7Sharp; break;
                     default: continue;
                  }
                  
                  numImages++;
                  JLabel image = new JLabel(icon);
                  dialogPnl.add(image);
               }
               ((FlowLayout)dialogPnl.getLayout()).setHgap(0);
               dialogPnl.setBackground(Color.DARK_GRAY);
               Insets insets = fr.getInsets();
               int anticipatedWidth = GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds().width - (insets.left + insets.right);
               dialogPnl.setPreferredSize(new Dimension(0,5 + 178*(1+(21*numImages)/anticipatedWidth)));
               classicSheet.add(scrollPane2);
               classicSheet.setVisible(true);
            
            }});
      classicSheet.setBounds(GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds());
      input.requestFocus();
      input.getInputMap().put(KeyStroke.getKeyStroke("ENTER"),"none");
      classicSheet.addWindowListener(new WindowAdapter(){public void windowClosing(WindowEvent e){
         numImages = 0;
         dialogPnl.removeAll();
      }});
      fr.getRootPane().setDefaultButton(button);
   }
   
   public static void main(String[] args)
   {
      new VP2CPConverter();
   }
}